# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testparent',
            name='parent_childs',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='v1.TestChild'),
        ),
        migrations.AlterField(
            model_name='testchild',
            name='child_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='testparent',
            name='parent_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
