---
    - name: nginx_service_install
      debug: msg="this is an empty action"

    # http://kb.linuxvirtualserver.org/wiki/IPVS_FULLNAT_and_SYNPROXY
    # ansible-playbook -i hosts --extra-vars "ngx_version=nginx_1.10.1" ngx-server.yml
    #
    - name: copy nginx binary files to remote nodes
      copy: src={{ngx_version}} dest=/data/exec/ directory_mode="u=rwx,g=rx,o=rx"

    - name: create soft link for nginx
      file: src=/data/exec/{{ngx_version}} dest=/data/exec/nginx state=link

    - name: set attribute for nginx binary file
      file: src=/data/exec/nginx/sbin/nginx mode="0755"

    - name: copy nginx service script file to remote nodes
      copy: src=nginx.service dest=/etc/init.d/nginx mode="0755"

    - name: create default nginx log directory
      file: path=/data/exec/nginx/logs state=directory mode=0755

    - name: create log directory for nginx
      file: path="/data/log/nginx" state=directory mode="0755"

    - name: add crontab entries for log_cut
      cron: name="log_cut_nginx" minute="0" job="/bin/sh /data/shell/log_cut_nginx.sh >/dev/null"

    - name: enable nginx service at booting
      service: name=nginx enabled=yes
